{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeName: {{ .Release.Name }}-media
{{- end }}