{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-media
spec:
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/snap/microk8s/common/default-storage/{{ .Release.Name }}"
  capacity:
    storage: {{ .Values.persistence.capacity }}
  persistentVolumeReclaimPolicy:
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}